"""test

Revision ID: 18819be2095d
Revises: 3eed81e6d92f
Create Date: 2025-09-13 13:51:48.420136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18819be2095d'
down_revision: Union[str, Sequence[str], None] = '3eed81e6d92f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE transactions MODIFY COLUMN type ENUM('telegram_stars','yookassa') NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE transactions MODIFY COLUMN type ENUM('telegram_stars') NOT NULL")
    # ### end Alembic commands ###
