"""Add NPSSurvey model

Revision ID: 321b13fd8e25
Revises: 0d6497c8e276
Create Date: 2025-10-08 16:56:51.467306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '321b13fd8e25'
down_revision: Union[str, Sequence[str], None] = '0d6497c8e276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nps_surveys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='Telegram user ID'),
    sa.Column('chat_id', sa.BigInteger(), nullable=False, comment='Telegram chat ID'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='Telegram username без @'),
    sa.Column('score', sa.Integer(), nullable=False, comment='Оценка от 0 до 10'),
    sa.Column('trigger_count', sa.Integer(), nullable=False, comment='Количество триггеров до опроса'),
    sa.Column('survey_message_id', sa.BigInteger(), nullable=True, comment='ID сообщения с опросом'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chat_id', 'created_at', name='unique_user_daily_response')
    )
    op.create_index(op.f('ix_nps_surveys_chat_id'), 'nps_surveys', ['chat_id'], unique=False)
    op.create_index(op.f('ix_nps_surveys_created_at'), 'nps_surveys', ['created_at'], unique=False)
    op.create_index(op.f('ix_nps_surveys_user_id'), 'nps_surveys', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nps_surveys_user_id'), table_name='nps_surveys')
    op.drop_index(op.f('ix_nps_surveys_created_at'), table_name='nps_surveys')
    op.drop_index(op.f('ix_nps_surveys_chat_id'), table_name='nps_surveys')
    op.drop_table('nps_surveys')
    # ### end Alembic commands ###
