"""feedback feature

Revision ID: 6a27aea0ed3d
Revises: df86845ac97a
Create Date: 2025-10-04 18:32:38.428399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6a27aea0ed3d'
down_revision: Union[str, Sequence[str], None] = 'df86845ac97a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_chat_registry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_chat_registry_chat_id'), 'admin_chat_registry', ['chat_id'], unique=False)
    op.create_index(op.f('ix_admin_chat_registry_username'), 'admin_chat_registry', ['username'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Telegram user ID'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='Telegram username без @'),
    sa.Column('first_name', sa.String(length=255), nullable=True, comment='Имя пользователя'),
    sa.Column('last_name', sa.String(length=255), nullable=True, comment='Фамилия пользователя'),
    sa.Column('message', sa.Text(), nullable=False, comment='Текст обращения'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='Прочитано админом'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_is_read'), 'feedback', ['is_read'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.alter_column('transactions', 'type',
               existing_type=mysql.ENUM('telegram_stars', 'yookassa', collation='utf8_unicode_ci'),
               type_=sa.Enum('YOOKASSA', 'TELEGRAM_STARS', name='subscriptiontype'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'type',
               existing_type=sa.Enum('YOOKASSA', 'TELEGRAM_STARS', name='subscriptiontype'),
               type_=mysql.ENUM('telegram_stars', 'yookassa', collation='utf8_unicode_ci'),
               existing_nullable=False)
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_is_read'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_admin_chat_registry_username'), table_name='admin_chat_registry')
    op.drop_index(op.f('ix_admin_chat_registry_chat_id'), table_name='admin_chat_registry')
    op.drop_table('admin_chat_registry')
    # ### end Alembic commands ###
