"""Add chat_info table for tracking bot chat memberships

Revision ID: 6a4cdec0dad2
Revises: b9aea335b6fd
Create Date: 2025-10-05 22:55:14.695537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6a4cdec0dad2'
down_revision: Union[str, Sequence[str], None] = 'b9aea335b6fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_type', sa.String(length=20), nullable=False),
    sa.Column('chat_title', sa.String(length=255), nullable=True),
    sa.Column('chat_username', sa.String(length=255), nullable=True),
    sa.Column('chat_description', sa.Text(), nullable=True),
    sa.Column('members_count', sa.String(length=50), nullable=True),
    sa.Column('added_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('added_by_username', sa.String(length=255), nullable=True),
    sa.Column('added_by_first_name', sa.String(length=255), nullable=True),
    sa.Column('added_by_last_name', sa.String(length=255), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bot_status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_info_chat_id'), 'chat_info', ['chat_id'], unique=True)
    op.create_index(op.f('ix_chat_info_id'), 'chat_info', ['id'], unique=False)
    op.drop_index(op.f('idx_chat_id'), table_name='admin_chat_registry')
    op.drop_index(op.f('idx_username'), table_name='admin_chat_registry')
    op.create_index(op.f('ix_admin_chat_registry_chat_id'), 'admin_chat_registry', ['chat_id'], unique=False)
    op.create_index(op.f('ix_admin_chat_registry_username'), 'admin_chat_registry', ['username'], unique=False)
    op.alter_column('feedback', 'user_id',
               existing_type=mysql.BIGINT(),
               comment='Telegram user ID',
               existing_nullable=False)
    op.alter_column('feedback', 'username',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               comment='Telegram username без @',
               existing_nullable=True)
    op.alter_column('feedback', 'first_name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               comment='Имя пользователя',
               existing_nullable=True)
    op.alter_column('feedback', 'last_name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               comment='Фамилия пользователя',
               existing_nullable=True)
    op.alter_column('feedback', 'message',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               comment='Текст обращения',
               existing_nullable=False)
    op.alter_column('feedback', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('feedback', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment='Прочитано админом',
               existing_server_default=sa.text("'0'"))
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_is_read'), 'feedback', ['is_read'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.drop_index(op.f('transaction_id'), table_name='transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('transaction_id'), 'transactions', ['transaction_id'], unique=True)
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_is_read'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    op.alter_column('feedback', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment=None,
               existing_comment='Прочитано админом',
               existing_server_default=sa.text("'0'"))
    op.alter_column('feedback', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('feedback', 'message',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Текст обращения',
               existing_nullable=False)
    op.alter_column('feedback', 'last_name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='Фамилия пользователя',
               existing_nullable=True)
    op.alter_column('feedback', 'first_name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='Имя пользователя',
               existing_nullable=True)
    op.alter_column('feedback', 'username',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='Telegram username без @',
               existing_nullable=True)
    op.alter_column('feedback', 'user_id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='Telegram user ID',
               existing_nullable=False)
    op.drop_index(op.f('ix_admin_chat_registry_username'), table_name='admin_chat_registry')
    op.drop_index(op.f('ix_admin_chat_registry_chat_id'), table_name='admin_chat_registry')
    op.create_index(op.f('idx_username'), 'admin_chat_registry', ['username'], unique=False)
    op.create_index(op.f('idx_chat_id'), 'admin_chat_registry', ['chat_id'], unique=False)
    op.drop_index(op.f('ix_chat_info_id'), table_name='chat_info')
    op.drop_index(op.f('ix_chat_info_chat_id'), table_name='chat_info')
    op.drop_table('chat_info')
    # ### end Alembic commands ###
