"""Add chat_info_history table

Revision ID: acebee9552ba
Revises: d6c43447b568
Create Date: 2025-10-06 21:32:17.461616

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "acebee9552ba"
down_revision: Union[str, Sequence[str], None] = "d6c43447b568"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_info_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "snapshot_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("chat_type", sa.String(length=20), nullable=False),
        sa.Column("chat_title", sa.String(length=255), nullable=True),
        sa.Column("chat_username", sa.String(length=255), nullable=True),
        sa.Column("chat_description", sa.Text(), nullable=True),
        sa.Column("members_count", sa.String(length=50), nullable=True),
        sa.Column("bot_status", sa.String(length=20), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_info_history_chat_id"),
        "chat_info_history",
        ["chat_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_info_history_id"), "chat_info_history", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_info_history_id"), table_name="chat_info_history")
    op.drop_index(op.f("ix_chat_info_history_chat_id"), table_name="chat_info_history")
    op.drop_table("chat_info_history")
    # ### end Alembic commands ###
