"""fix user_id

Revision ID: b9aea335b6fd
Revises: 6a27aea0ed3d
Create Date: 2025-10-04 19:42:06.538227

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "b9aea335b6fd"
down_revision: Union[str, Sequence[str], None] = "6a27aea0ed3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "feedback",
        "user_id",
        existing_type=mysql.INTEGER(display_width=11),
        type_=sa.BigInteger(),
        existing_comment="Telegram user ID",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "feedback",
        "user_id",
        existing_type=sa.BigInteger(),
        type_=mysql.INTEGER(display_width=11),
        existing_comment="Telegram user ID",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
