"""Add chat_info table for tracking bot chat memberships

Revision ID: d6c43447b568
Revises: 6a4cdec0dad2
Create Date: 2025-10-05 22:55:59.837512

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d6c43447b568"
down_revision: Union[str, Sequence[str], None] = "6a4cdec0dad2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
