"""new pay type

Revision ID: df86845ac97a
Revises: 9d8bbbcf8846
Create Date: 2025-09-13 14:19:09.510068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df86845ac97a'
down_revision: Union[str, Sequence[str], None] = '9d8bbbcf8846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE transactions MODIFY COLUMN type ENUM('telegram_stars','yookassa') NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE transactions MODIFY COLUMN type ENUM('telegram_stars') NOT NULL")
    # ### end Alembic commands ###
